# Generated by Django 4.0.6 on 2022-09-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_recipe_date_alter_story_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_of_recipe', to='story.recipe'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_of_story', to='story.story'),
        ),
    ]
